<a href="https://colab.research.google.com/github/VivekShahare04/ML-Projects/blob/main/Multioutput_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

In [15]:
inputs = np.array([[23,45,67],
                   [34,67,54],
                   [34,23,13],
                   [56,87,98],
                   [56,76,34]],dtype = 'float32')
inputs.shape

(5, 3)

In [17]:
targets = np.array([[34,76],[56,87],[45,56],[98,32],[76,65]],dtype='float32')
targets.shape

(5, 2)

In [18]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[23., 45., 67.],
        [34., 67., 54.],
        [34., 23., 13.],
        [56., 87., 98.],
        [56., 76., 34.]])
tensor([[34., 76.],
        [56., 87.],
        [45., 56.],
        [98., 32.],
        [76., 65.]])


In [19]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.1071e+00,  8.7209e-01,  9.8732e-04],
        [-7.0248e-03,  8.1591e-01, -2.3729e-01]], requires_grad=True)
tensor([-0.5026,  1.0934], requires_grad=True)


In [20]:
w.shape ,b.shape

(torch.Size([2, 3]), torch.Size([2]))

In [21]:
def model(x):
  return x @ w.t() + b;

In [22]:
prediction = model(inputs)
prediction

tensor([[ 13.3441,  21.7496],
        [ 20.3391,  42.7071],
        [-18.0733,  16.5358],
        [ 13.4679,  48.4301],
        [  3.8118,  54.6415]], grad_fn=<AddBackward0>)

In [23]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [24]:
loss = mse(prediction,targets)
loss

tensor(2487.3062, grad_fn=<DivBackward0>)

In [25]:
loss.backward()

In [26]:
w.shape,b.shape

(torch.Size([2, 3]), torch.Size([2]))

In [27]:
w.grad,b.grad

(tensor([[-2521.6770, -3522.0154, -2973.6255],
         [ -751.0980, -1134.8789, -1056.3330]]),
 tensor([-55.2221, -26.3872]))

In [29]:
for i in range(20):
  prediction=model(inputs)
  loss = mse(prediction,targets)
  print(f'epochs:{i},loss: {loss.item()}')
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

epochs:0,loss: 2487.30615234375
epochs:1,loss: 1931.340087890625
epochs:2,loss: 1735.874755859375
epochs:3,loss: 1574.2408447265625
epochs:4,loss: 1440.544921875
epochs:5,loss: 1329.9207763671875
epochs:6,loss: 1238.349853515625
epochs:7,loss: 1162.5137939453125
epochs:8,loss: 1099.6722412109375
epochs:9,loss: 1047.5628662109375
epochs:10,loss: 1004.31689453125
epochs:11,loss: 968.3914794921875
epochs:12,loss: 938.5130004882812
epochs:13,loss: 913.62890625
epochs:14,loss: 892.8707275390625
epochs:15,loss: 875.5208129882812
epochs:16,loss: 860.9869384765625
epochs:17,loss: 848.7796630859375
epochs:18,loss: 838.4952392578125
epochs:19,loss: 829.8001708984375


In [30]:
targets

tensor([[34., 76.],
        [56., 87.],
        [45., 56.],
        [98., 32.],
        [76., 65.]])

In [31]:
prediction

tensor([[51.4646, 34.7569],
        [65.4000, 57.5377],
        [ 1.8823, 22.6817],
        [82.1906, 71.2877],
        [52.5973, 70.0220]], grad_fn=<AddBackward0>)