<a href="https://colab.research.google.com/github/VivekShahare04/ML-Projects/blob/main/pytorchNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
from torch.utils.data import Dataset,DataLoader,TensorDataset

In [5]:
x = torch.arange(13,dtype=torch.float16)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       dtype=torch.float16)

In [8]:
data_loader = DataLoader(x)
for item in data_loader:
  print(item)

tensor([0.], dtype=torch.float16)
tensor([1.], dtype=torch.float16)
tensor([2.], dtype=torch.float16)
tensor([3.], dtype=torch.float16)
tensor([4.], dtype=torch.float16)
tensor([5.], dtype=torch.float16)
tensor([6.], dtype=torch.float16)
tensor([7.], dtype=torch.float16)
tensor([8.], dtype=torch.float16)
tensor([9.], dtype=torch.float16)
tensor([10.], dtype=torch.float16)
tensor([11.], dtype=torch.float16)
tensor([12.], dtype=torch.float16)


In [9]:
data_loader = DataLoader(x,batch_size=3,shuffle=True)
for i,batch in enumerate(data_loader):
  print(i,batch)

0 tensor([9., 0., 4.], dtype=torch.float16)
1 tensor([10.,  3.,  1.], dtype=torch.float16)
2 tensor([ 5., 11., 12.], dtype=torch.float16)
3 tensor([2., 7., 8.], dtype=torch.float16)
4 tensor([6.], dtype=torch.float16)


In [10]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=10)
X.shape,y.shape

((10, 20), (10,))

In [11]:
dataset = TensorDataset(torch.tensor(X),torch.tensor(y))
dataset